# Generated by Django 6.0.2 on 2026-02-18 22:27

import core.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('razao_social', models.CharField(max_length=200)),
                ('nome_fantasia', models.CharField(max_length=200)),
                ('inscricao_municipal', models.CharField(blank=True, max_length=50)),
                ('tipo', models.CharField(choices=[('matriz', 'Matriz'), ('filial', 'Filial')], max_length=10)),
                ('ativo', models.BooleanField(default=True)),
                ('certificado_thumbprint', models.CharField(blank=True, max_length=40)),
                ('certificado_senha', models.CharField(blank=True, max_length=255)),
                ('certificado_validade', models.DateField(blank=True, null=True)),
                ('certificado_emitente', models.CharField(blank=True, max_length=255)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ultimo_download', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_nota', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('ambos', 'Ambos')], max_length=10)),
                ('dia_mes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('periodo_inicio', models.IntegerField(default=1)),
                ('periodo_fim_tipo', models.CharField(choices=[('ultimo_dia', 'Último dia do mês'), ('fixo', 'Dia fixo')], max_length=10)),
                ('periodo_fim_dia', models.IntegerField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('horario_preferencial', models.TimeField(default='23:00')),
                ('notificar_email', models.BooleanField(default=False)),
                ('compactar_auto', models.BooleanField(default=True)),
                ('ultima_execucao', models.DateTimeField(blank=True, null=True)),
                ('proxima_execucao', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_nota', models.CharField(max_length=10)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('periodo_busca_inicio', models.DateField()),
                ('periodo_busca_fim', models.DateField()),
                ('quantidade_notas', models.IntegerField(default=0)),
                ('quantidade_sucesso', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('sucesso', 'Sucesso'), ('parcial', 'Parcial'), ('erro', 'Erro')], max_length=20)),
                ('arquivo_zip', models.FileField(blank=True, upload_to='zips/')),
                ('log_detalhado', models.TextField(blank=True)),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('chave_acesso', models.CharField(max_length=44, unique=True)),
                ('data_emissao', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tomador_cnpj', models.CharField(blank=True, max_length=18)),
                ('tomador_nome', models.CharField(blank=True, max_length=200)),
                ('arquivo_pdf', models.FileField(upload_to='pdfs/')),
                ('arquivo_xml', models.FileField(upload_to='xmls/')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('data_download', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('historico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='core.historicodownload')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[core.models.validar_cpf])),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('foto', models.ImageField(blank=True, upload_to='fotos/')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='historicodownload',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pessoa'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='usuarios',
            field=models.ManyToManyField(related_name='empresas', to='core.pessoa'),
        ),
    ]
