# Generated by Django 6.0.2 on 2026-02-18 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['nome_fantasia'], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='historicodownload',
            options={'ordering': ['-data_inicio'], 'verbose_name': 'Histórico de Download', 'verbose_name_plural': 'Históricos de Download'},
        ),
        migrations.AlterModelOptions(
            name='notafiscal',
            options={'ordering': ['-data_emissao'], 'verbose_name': 'Nota Fiscal', 'verbose_name_plural': 'Notas Fiscais'},
        ),
        migrations.AlterModelOptions(
            name='pessoa',
            options={'verbose_name': 'Pessoa', 'verbose_name_plural': 'Pessoas'},
        ),
        migrations.AddField(
            model_name='agendamento',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='bairro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cep',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='empresa',
            name='certificado_arquivo',
            field=models.FileField(blank=True, null=True, upload_to='certificados/'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='complemento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='empresa',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='empresa',
            name='logradouro',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='empresa',
            name='municipio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='empresa',
            name='numero',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='empresa',
            name='uf',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='periodo_fim_tipo',
            field=models.CharField(choices=[('ultimo_dia', 'Último dia do mês'), ('fixo', 'Dia fixo')], default='ultimo_dia', max_length=10),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='tipo',
            field=models.CharField(choices=[('matriz', 'Matriz'), ('filial', 'Filial')], default='matriz', max_length=10),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='usuarios',
            field=models.ManyToManyField(blank=True, related_name='empresas', to='core.pessoa'),
        ),
        migrations.AlterField(
            model_name='historicodownload',
            name='arquivo_zip',
            field=models.FileField(blank=True, null=True, upload_to='zips/'),
        ),
        migrations.AlterField(
            model_name='historicodownload',
            name='data_fim',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicodownload',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='historicodownload',
            name='status',
            field=models.CharField(choices=[('sucesso', 'Sucesso'), ('parcial', 'Parcial'), ('erro', 'Erro')], default='erro', max_length=20),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='arquivo_xml',
            field=models.FileField(blank=True, null=True, upload_to='xmls/'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pessoa', to=settings.AUTH_USER_MODEL),
        ),
    ]
