# Generated by Django 6.0.2 on 2026-02-19 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_client_api_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={},
        ),
        migrations.CreateModel(
            name='TarefaDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_nota', models.CharField(max_length=10)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_inicio_execucao', models.DateTimeField(blank=True, null=True)),
                ('data_fim_execucao', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando'), ('processando', 'Processando'), ('extraindo_links', 'Extraindo Links'), ('baixando', 'Baixando Notas'), ('concluido', 'Concluído'), ('erro', 'Erro'), ('zipando', 'Zipando Arquivos')], default='aguardando', max_length=20)),
                ('progresso', models.IntegerField(default=0)),
                ('mensagem', models.TextField(blank=True)),
                ('total_notas', models.IntegerField(default=0)),
                ('notas_baixadas', models.IntegerField(default=0)),
                ('notas_erro', models.IntegerField(default=0)),
                ('pasta_destino', models.CharField(blank=True, max_length=500)),
                ('arquivo_zip', models.FileField(blank=True, null=True, upload_to='zips/')),
                ('logs', models.TextField(blank=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pessoa')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
            },
        ),
    ]
