# Generated by Django 6.0.2 on 2026-02-19 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_layoutbancario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layoutbancario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='layoutbancario',
            name='identificadores',
            field=models.TextField(blank=True, help_text='Palavras-chave separadas por vírgula para detectar o banco no texto do PDF/OFX'),
        ),
        migrations.AlterField(
            model_name='layoutbancario',
            name='template_html',
            field=models.TextField(blank=True, help_text='HTML usado como template para gerar o PDF a partir do OFX'),
        ),
        migrations.CreateModel(
            name='ArquivoConversao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_original', models.FileField(upload_to='conversor/originais/')),
                ('arquivo_convertido', models.FileField(blank=True, null=True, upload_to='conversor/convertidos/')),
                ('nome_original', models.CharField(max_length=255)),
                ('formato_origem', models.CharField(max_length=10)),
                ('formato_destino', models.CharField(max_length=10)),
                ('tamanho_original', models.IntegerField(default=0)),
                ('tamanho_convertido', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('convertendo', 'Convertendo'), ('concluido', 'Concluído'), ('erro', 'Erro')], default='pendente', max_length=20)),
                ('mensagem_erro', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_conversao', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pessoa')),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
    ]
