# Generated by Django 6.0.2 on 2026-02-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_layoutbancario_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('codename', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('permissions', models.TextField(blank=True, help_text='Códigos de permissão separados por vírgula, ex.: empresa.edit,certificado.manage')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pessoas', models.ManyToManyField(blank=True, related_name='roles', to='core.pessoa')),
            ],
            options={
                'verbose_name': 'Papel (Role)',
                'verbose_name_plural': 'Papéis (Roles)',
            },
        ),
    ]
