# Generated by Django 6.0.2 on 2026-02-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='permissions',
            field=models.TextField(blank=True, help_text='Códigos de permissão separados por vírgula, ex.: empresa.edit,certificado.manage'),
        ),
    ]
