# Generated by Django 6.0.2 on 2026-02-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_pessoa_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='impostos',
            field=models.JSONField(blank=True, help_text='Dicionário com valores de impostos extraídos do XML', null=True),
        ),
    ]
