# Generated by Django 6.0.2 on 2026-02-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_notafiscal_impostos'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='ultimo_zip',
            field=models.FileField(blank=True, help_text='Último arquivo ZIP gerado para esta empresa', null=True, upload_to='empresas/zips/'),
        ),
    ]
