# Generated by Django 6.0.2 on 2026-02-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_empresa_ultimo_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='certificado_antigo',
            field=models.BooleanField(default=False, help_text='Certificado usa algoritmo antigo (legacy)'),
        ),
    ]
