# Generated by Django 6.0.2 on 2026-02-27 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_default_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivoconversao',
            name='banco',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='SiegCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_key', models.TextField(blank=True, help_text='Chave da API cifrada', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sieg_credential', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
