# Generated by Django 6.0.2 on 2026-02-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_delete_siegcredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='certificado_antigo',
            field=models.BooleanField(default=False),
        ),
    ]
