# Generated by Django 6.0.2 on 2026-03-02 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_last_read_conversationparticipant'),
        ('painel', '0008_chatpresence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='chat_anexos/%Y/%m/%d/')),
                ('nome_original', models.CharField(max_length=255)),
                ('tamanho', models.IntegerField(help_text='Tamanho em bytes')),
                ('tipo', models.CharField(help_text='MIME type', max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('participantes', models.ManyToManyField(related_name='conversas', to='core.pessoa')),
            ],
            options={
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('delivered', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('lida', models.BooleanField(default=False)),
                ('lida_em', models.DateTimeField(blank=True, null=True)),
                ('anexos', models.ManyToManyField(blank=True, related_name='mensagens', to='core.anexomensagem')),
                ('atendimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_core', related_query_name='mensagens_core', to='painel.atendimento')),
                ('conversa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='core.conversa')),
                ('remetente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_enviadas', to='core.pessoa')),
            ],
            options={
                'ordering': ['criado_em'],
                'indexes': [models.Index(fields=['conversa', 'criado_em'], name='core_mensag_convers_2d4ef6_idx'), models.Index(fields=['atendimento', 'criado_em'], name='core_mensag_atendim_c6483f_idx')],
            },
        ),
    ]
