# Generated by Django 6.0.2 on 2026-02-28 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analista',
            options={'permissions': []},
        ),
        migrations.AlterModelOptions(
            name='atendimento',
            options={'permissions': []},
        ),
        migrations.AlterModelOptions(
            name='departamento',
            options={'permissions': []},
        ),
    ]
