# Generated by assistant to add AtendimentoAnexo model
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0002_alter_analista_options_alter_atendimento_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtendimentoAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='painel/anexos/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='painel.atendimento', related_name='anexos')),
            ],
            options={
                'verbose_name': 'Anexo de Atendimento',
                'verbose_name_plural': 'Anexos de Atendimento',
            },
        ),
    ]
