# Generated by Django 6.0.2 on 2026-02-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0004_add_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
