# Generated by Django 6.0.2 on 2026-03-01 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_empresa_certificado_antigo'),
        ('painel', '0006_analista_disponivel_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='empresa_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos', to='core.empresa'),
        ),
    ]
